global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8000']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth:8001']

  - job_name: 'model-registry'
    static_configs:
      - targets: ['model-registry:8002']

  - job_name: 'inference-service'
    static_configs:
      - targets: ['inference:8003']